### ISSUE TITLE
scaling it

### ISSUE THREAD

**Issue by abelrugaju** [aws-samples/amazon-rekognition-virtual-proctor#19]
Hello everyone,
first of all am really new at this.So here is my question .Is there anyway u can change for me the code so that i can look at the students as they do their test. Because i thought the system would be able to allow me look at the student while detecting the number of people in the room plus alerting me whose invigilating them. Let me put it this way. 

Is there anyway i can have a solution where by the studensts would log in. Then it would allow me to see them while there doing there exam plus detecting objects and extra people in the room and notifying me via SNS.
That my humble question. Otherwise its a very nice system you designed here Sir.

i would be grateful if anyone can help me out here.

regards,
Abel

**Comment by ConnorKirk** [comment]
Hi Abel,

Thanks for creating an issue.
My understanding is that you would like to use this sample to invigilate students, providing a login for each student, as well as being able to monitor multiple students.
Unfortunately this sample is intended only to show the how AWS Rekognition be used to assist in virtually proctoring exams, and doesn't have all the features you require.

An [AWS Partner](https://aws.amazon.com/partners/) may be able to help you create a solution like you describe. Alternatively, there may be a pre-existing product that meets your requirements.

I'm sorry I can't be more helpful.
