### ISSUE TITLE
upload-custom-bucket command missing 

### ISSUE THREAD

**Issue by mayordwells** [aws-samples/amazon-rekognition-virtual-proctor#20]
Currently following this instruction to enable me to customize this solution. - https://github.com/aws-samples/amazon-rekognition-virtual-proctor/blob/master/CONTRIBUTING.md#working-with-the-web-ui

I am getting an error on running the command `CUSTOM_BUCKET=<your bucket> npm run upload-custom-bucket`

It returns the error - `npm ERR! missing script: upload-custom-bucket`

How can I find the script/command for this, please?

**Comment by matteofigus** [comment]
Hi @mayordwells, thanks for submitting an issue. I am sorry for the inconvenience. I am working on a fix right now, I'll update this thread as soon as the script is available.

**Comment by mayordwells** [comment]
Thanks for your prompt reply @matteofigus I'll be waiting.

**Comment by matteofigus** [comment]
@mayordwells can you retry now? Just updated the scripts and the docs.

**Comment by mayordwells** [comment]
Thanks @matteofigus i'll do that and update you ASAP. Thanks!

**Comment by mayordwells** [comment]
Hi @matteofigus so I've tested and the commands work now. I was able to deploy successfully. Thanks!
